package modelo;
// Generated 22 ene. 2022 20:08:16 by Hibernate Tools 5.4.32.Final

/**
 * DatosElectorales generated by hbm2java
 */
public class DatosElectorales implements java.io.Serializable {

	private int id;
	private int edad;
	private String votoPartido;
	private String comunidad;

	public DatosElectorales() {
	}

	public DatosElectorales(int id, int edad, String votoPartido, String comunidad) {
		this.id = id;
		this.edad = edad;
		this.votoPartido = votoPartido;
		this.comunidad = comunidad;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getEdad() {
		return this.edad;
	}

	public void setEdad(int edad) {
		this.edad = edad;
	}

	public String getVotoPartido() {
		return this.votoPartido;
	}

	public void setVotoPartido(String votoPartido) {
		this.votoPartido = votoPartido;
	}

	public String getComunidad() {
		return this.comunidad;
	}

	public void setComunidad(String comunidad) {
		this.comunidad = comunidad;
	}

}
